CREATE TABLE EMPLOYEES(
EMP_ID INT PRIMARY KEY,
EMP_NAME VARCHAR(20), 
AGE INT CHECK(AGE>=18),
EMAIL VARCHAR(20) UNIQUE,
MOBILE_NUMBER  INT UNIQUE
)


INSERT INTO  EMPLOYEES(EMP_ID,EMP_NAME,AGE,EMAIL,MOBILE_NUMBER) 
VALUES(101,'AKASH',18,'ABC@GMAIL.COM',123)

INSERT INTO  EMPLOYEES(EMP_ID,EMP_NAME,AGE,EMAIL,MOBILE_NUMBER) 
VALUES(102,'VIAKS',19,'C@GMAIL.COM',1234)


INSERT INTO  EMPLOYEES(EMP_ID,EMP_NAME,AGE,EMAIL,MOBILE_NUMBER) 
VALUES(104,NULL,19,'CS@GMAIL.COM',12348)


SELECT EMP_NAME FROM  EMPLOYEES
WHERE EMP_ID=102



UPDATE EMPLOYEES
SET EMP_NAME='VIJAY'
WHERE EMP_ID=104


DELETE FROM EMPLOYEES
WHERE EMP_ID =104;


SELECT * FROM EMPLOYEES
